/**
 * Calendar / workspace exports.
 *
 * Every exporter keeps the same shape the brief specifies:
 *   - one topic per event per day
 *   - event title:       "[Subject] – [Topic]"
 *   - event description: the checklist of tasks for that day
 */

import { fromISODate, toICSLocalStamp, toICSStamp } from './dates.js';

export const DEFAULT_START_TIME = '18:00';
export const DEFAULT_DURATION_MINUTES = 60;

/** "[Subject] – [Topic]" (en dash, per the brief). */
export function eventTitle(session) {
  return session.subject ? `${session.subject} – ${session.topic}` : session.topic;
}

/** Checklist rendered as the event body. */
export function eventDescription(session) {
  const lines = [];
  if (session.repLabel) {
    lines.push(`${session.repLabel} — pass ${session.repIndex + 1} of ${session.repCount}`);
    lines.push('');
  }
  lines.push('Checklist:');
  for (const task of session.tasks || []) {
    lines.push(`☐ ${task.text}${task.minutes ? ` (${task.minutes} min)` : ''}`);
  }
  const total = (session.tasks || []).reduce((sum, t) => sum + (t.minutes || 0), 0);
  if (total) {
    lines.push('');
    lines.push(`Total: ~${total} minutes.`);
  }
  lines.push('');
  lines.push('Generated by Study Buddy.');
  return lines.join('\n');
}

/** Start/end `Date`s for a session, given a time of day. */
export function sessionTimes(session, startTime = DEFAULT_START_TIME, durationMinutes) {
  const [hh, mm] = String(startTime).split(':').map(Number);
  const base = session.date instanceof Date ? new Date(session.date) : fromISODate(session.iso);
  const start = new Date(base.getFullYear(), base.getMonth(), base.getDate(), hh || 0, mm || 0, 0, 0);

  const planned = (session.tasks || []).reduce((sum, t) => sum + (t.minutes || 0), 0);
  const minutes = durationMinutes || Math.max(30, Math.ceil((planned || DEFAULT_DURATION_MINUTES) / 15) * 15);
  const end = new Date(start.getTime() + minutes * 60 * 1000);
  return { start, end, minutes };
}

/* ------------------------------------------------------------------ CSV -- */

function csvCell(value) {
  const text = String(value ?? '');
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

/**
 * CSV export. Column names match Google Calendar's import format, so the same
 * file works for Google Calendar *and* opens straight into Excel or Sheets.
 */
export function toCSV(sessions, { startTime = DEFAULT_START_TIME } = {}) {
  const header = [
    'Subject',
    'Start Date',
    'Start Time',
    'End Date',
    'End Time',
    'All Day Event',
    'Description',
    'Location',
    'Private',
  ];

  const fmtDate = (d) => `${String(d.getMonth() + 1).padStart(2, '0')}/${String(d.getDate()).padStart(2, '0')}/${d.getFullYear()}`;
  const fmtTime = (d) => {
    const h = d.getHours();
    const suffix = h >= 12 ? 'PM' : 'AM';
    const hour12 = h % 12 === 0 ? 12 : h % 12;
    return `${hour12}:${String(d.getMinutes()).padStart(2, '0')} ${suffix}`;
  };

  const rows = sessions.map((session) => {
    const { start, end } = sessionTimes(session, startTime);
    return [
      eventTitle(session),
      fmtDate(start),
      fmtTime(start),
      fmtDate(end),
      fmtTime(end),
      'False',
      eventDescription(session).replace(/\n/g, ' \\n '),
      '',
      'True',
    ].map(csvCell);
  });

  return [header.join(','), ...rows.map((r) => r.join(','))].join('\r\n');
}

/** A flatter CSV for spreadsheet work — one row per task, easy to pivot. */
export function toTaskCSV(sessions) {
  const header = ['Date', 'Week', 'Subject', 'Topic', 'Pass', 'Difficulty', 'Task', 'Est. minutes'];
  const rows = [];
  for (const session of sessions) {
    for (const task of session.tasks || []) {
      rows.push(
        [
          session.iso,
          Math.floor(session.dayIndex / 7) + 1,
          session.subject,
          session.topic,
          session.repLabel || `Pass ${session.repIndex + 1}`,
          session.difficulty,
          task.text,
          task.minutes || '',
        ].map(csvCell),
      );
    }
  }
  return [header.join(','), ...rows.map((r) => r.join(','))].join('\r\n');
}

/* ------------------------------------------------------- iCal / Google -- */

function icsEscape(text) {
  return String(text)
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\n/g, '\\n');
}

/** Fold long lines at 75 octets, as RFC 5545 requires. */
function icsFold(line) {
  if (line.length <= 75) return line;
  const parts = [line.slice(0, 75)];
  let rest = line.slice(75);
  while (rest.length > 74) {
    parts.push(` ${rest.slice(0, 74)}`);
    rest = rest.slice(74);
  }
  if (rest) parts.push(` ${rest}`);
  return parts.join('\r\n');
}

/**
 * iCalendar file — imports into Google Calendar, Apple Calendar, Outlook.
 * One VEVENT per session, so one topic per day is preserved.
 */
export function toICS(sessions, { startTime = DEFAULT_START_TIME, calendarName = 'Study Buddy Revision' } = {}) {
  const stamp = toICSStamp(new Date());
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Study Buddy//Spaced Repetition Planner//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${icsEscape(calendarName)}`,
  ];

  sessions.forEach((session, index) => {
    const { start, end } = sessionTimes(session, startTime);
    lines.push(
      'BEGIN:VEVENT',
      `UID:${session.id || `s${index}`}-${session.iso}@study-buddy`,
      `DTSTAMP:${stamp}`,
      // Floating local time — see toICSLocalStamp. 18:00 must stay 18:00.
      `DTSTART:${toICSLocalStamp(start)}`,
      `DTEND:${toICSLocalStamp(end)}`,
      icsFold(`SUMMARY:${icsEscape(eventTitle(session))}`),
      icsFold(`DESCRIPTION:${icsEscape(eventDescription(session))}`),
      'BEGIN:VALARM',
      'TRIGGER:-PT30M',
      'ACTION:DISPLAY',
      icsFold(`DESCRIPTION:${icsEscape(`Study session: ${eventTitle(session)}`)}`),
      'END:VALARM',
      'END:VEVENT',
    );
  });

  lines.push('END:VCALENDAR');
  return lines.join('\r\n');
}

/**
 * A "add this one event" Google Calendar link. Useful for adding a single
 * session without importing the whole calendar.
 */
export function googleCalendarLink(session, { startTime = DEFAULT_START_TIME } = {}) {
  const { start, end } = sessionTimes(session, startTime);
  // Same floating local wall time as the .ics, so both routes agree.
  const fmt = toICSLocalStamp;

  const params = new URLSearchParams({
    action: 'TEMPLATE',
    text: eventTitle(session),
    dates: `${fmt(start)}/${fmt(end)}`,
    details: eventDescription(session),
  });
  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

/* ------------------------------------------------------------- Notion -- */

/**
 * Notion-ready markdown. Pasting this into a Notion page produces a heading
 * per week, a toggle-friendly block per day, and real checkboxes for tasks.
 */
export function toNotionMarkdown(sessions, { title = 'Revision Plan' } = {}) {
  const out = [`# ${title}`, ''];
  let currentWeek = -1;

  for (const session of sessions) {
    const week = Math.floor(session.dayIndex / 7) + 1;
    if (week !== currentWeek) {
      currentWeek = week;
      out.push(`## Week ${week}`, '');
    }
    out.push(`### ${session.iso} — ${eventTitle(session)}`);
    out.push(`*${session.repLabel || `Pass ${session.repIndex + 1}`} · difficulty: ${session.difficulty}*`, '');
    for (const task of session.tasks || []) {
      out.push(`- [ ] ${task.text}${task.minutes ? ` *(${task.minutes} min)*` : ''}`);
    }
    out.push('');
  }

  return out.join('\n');
}

/**
 * A Notion database import (CSV). Each row becomes a page with Date, Subject,
 * Topic, Pass and Tasks properties.
 */
export function toNotionCSV(sessions) {
  const header = ['Name', 'Date', 'Subject', 'Topic', 'Pass', 'Difficulty', 'Tasks', 'Status'];
  const rows = sessions.map((session) =>
    [
      eventTitle(session),
      session.iso,
      session.subject,
      session.topic,
      session.repLabel || `Pass ${session.repIndex + 1}`,
      session.difficulty,
      (session.tasks || []).map((t) => `• ${t.text}`).join('\n'),
      'Not started',
    ].map(csvCell),
  );
  return [header.join(','), ...rows.map((r) => r.join(','))].join('\r\n');
}
